# Generated by Django 5.1.7 on 2025-03-25 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('anticonceptivo', 'Anticonceptivo'), ('hormonal', 'Tratamiento Hormonal'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('dosis_default', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CicloMenstrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del ciclo (primer día de menstruación)')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin del ciclo (último día antes del siguiente ciclo)', null=True)),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='Duración total del ciclo en días', null=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('duracion_ciclo_promedio', models.PositiveIntegerField(default=28, help_text='Duración promedio del ciclo en días')),
                ('duracion_periodo_promedio', models.PositiveIntegerField(default=5, help_text='Duración promedio del período en días')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('medicacion', 'Medicación'), ('cita_medica', 'Cita médica'), ('inicio_periodo', 'Inicio de período esperado'), ('otro', 'Otro')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('ciclo', 'Basada en ciclo'), ('unica', 'Única vez')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('es_dia_periodo', models.BooleanField(default=False)),
                ('flujo_menstrual', models.CharField(blank=True, choices=[('nulo', 'Nulo'), ('ligero', 'Ligero'), ('moderado', 'Moderado'), ('abundante', 'Abundante'), ('muy_abundante', 'Muy abundante')], max_length=15, null=True)),
                ('estados_animo', models.CharField(blank=True, help_text='Separados por comas si hay varios', max_length=100)),
                ('dolor', models.PositiveIntegerField(blank=True, help_text='Escala de 0-10', null=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('ciclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='moiraflow.ciclomenstrual')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='RegistroMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_toma', models.TimeField(blank=True, null=True)),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('tomado', models.BooleanField(default=False)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moiraflow.medicamento')),
                ('registro_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_tomados', to='moiraflow.registrodiario')),
            ],
            options={
                'unique_together': {('registro_diario', 'medicamento')},
            },
        ),
        migrations.CreateModel(
            name='RegistroSintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidad', models.PositiveIntegerField(choices=[(1, 'Muy leve'), (2, 'Leve'), (3, 'Moderado'), (4, 'Intenso'), (5, 'Muy intenso')], default=3)),
                ('notas', models.TextField(blank=True)),
                ('registro_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintomas', to='moiraflow.registrodiario')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moiraflow.sintoma')),
            ],
            options={
                'unique_together': {('registro_diario', 'sintoma')},
            },
        ),
    ]
